changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: 🚀 Features
      labels:
        - enhancement
        - feature
    - title: 🐛 Bug Fixes
      labels:
        - bug
        - bugfix
        - fix
    - title: ⚠️ Breaking Changes
      labels:
        - breaking-change
    - title: 📝 Documentation
      labels:
        - documentation
    - title: ⚡ Performance
      labels:
        - performance
    - title: 🔧 Maintenance
      labels:
        - maintenance
        - dependencies
    - title: Other Changes
      labels:
        - "*"
