repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # Essential checks
      - id: check-ast  # Catch Python syntax errors
      - id: check-yaml  # Catch YAML syntax errors
      - id: check-json  # Catch JSON syntax errors
      - id: check-merge-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace

      # Security and large files
      - id: check-added-large-files

      # File integrity
      - id: check-case-conflict  # Important for cross-platform projects
      - id: check-executables-have-shebangs
      - id: check-symlinks

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.5
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [ python, pyi ]
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
        types_or: [ python, pyi ]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true

      - id: branch-name
        name: Check branch naming convention
        entry: python -c 'from git import Repo; import sys, re; repo = Repo("."); branch = repo.active_branch.name; patterns = ["^feature/", "^bugfix/", "^hotfix/", "^release/", "^ci/", "^refactor/", "^main$"]; sys.exit(1) if not any(re.match(p, branch) for p in patterns) else print(f"Branch name {branch} follows convention")'
        language: system
        pass_filenames: false
        always_run: true

      - id: no-commit-to-main
        name: Prevent commits to main branch
        entry: python -c 'from git import Repo; import sys; repo = Repo("."); sys.exit(1) if repo.active_branch.name == "main" else 0'
        language: system
        stages: [pre-commit]
        pass_filenames: false
        always_run: true
