coverage:
  status:
    project:
      default:
        target: 85%
        threshold: 1%
        if_ci_failed: error
        informational: false
        only_pulls: false
    patch:
      default:
        target: 90%
        threshold: 1%
        if_ci_failed: error
        informational: false
        only_pulls: true

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true

github_checks:
  annotations: true
