name: Branch Protection Rules

on:
  # This workflow is triggered when branch protection settings need to be updated
  workflow_dispatch:
  # Also run when the repository is first created/setup
  create:

permissions:
  contents: write
  pull-requests: write
  actions: write

jobs:
  protection:
    name: Set Branch Protection
    runs-on: ubuntu-latest
    steps:
      - name: Set Branch Protection Rules
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ADMIN_TOKEN }}
          script: |
            await github.rest.repos.updateBranchProtection({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: 'main',
              required_status_checks: {
                strict: true,
                contexts: ['test', 'lint']
              },
              enforce_admins: true,
              required_pull_request_reviews: {
                required_approving_review_count: 1,
                dismiss_stale_reviews: true,
                require_code_owner_reviews: true
              },
              restrictions: null,
              required_linear_history: true,
              allow_force_pushes: false,
              allow_deletions: false
            });
