name: Branch Protection Rules

on:
  # This workflow is triggered when branch protection settings need to be updated
  workflow_dispatch:
  # Also run when the repository is first created/setup
  create:

permissions:
  contents: write
  pull-requests: write
  actions: write

jobs:
  protection:
    name: Set Branch Protection
    runs-on: ubuntu-latest
    steps:
      - name: Set Branch Protection Rules
        env:
          GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}
        run: |
          gh api \
            --method PUT \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/branches/main/protection \
            -f required_status_checks='{"strict":true,"contexts":["test","lint"]}' \
            -f enforce_admins=true \
            -f required_pull_request_reviews='{"required_approving_review_count":1,"dismiss_stale_reviews":true,"require_code_owner_reviews":true}' \
            -f restrictions=null \
            -f required_linear_history=true \
            -f allow_force_pushes=false \
            -f allow_deletions=false
