name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag to release'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install dependencies
        run: uv sync

      - name: Build package
        run: uv pip install --system build && python -m build

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ inputs.tag }} \
            --title "Release ${{ inputs.tag }}" \
            --generate-notes \
            dist/*

      - name: Publish to PyPI
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          uv pip install --system twine
          python -m twine upload \
            --username __token__ \
            --password $PYPI_TOKEN \
            dist/*
