name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag to release'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: uv pip install --system -e .[dev]

      - name: Build package
        run: uv pip install --system build && python -m build

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ inputs.tag }} \
            --title "Release ${{ inputs.tag }}" \
            --generate-notes \
            dist/*

      - name: Publish to PyPI
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          uv pip install --system twine
          python -m twine upload \
            --username __token__ \
            --password $PYPI_TOKEN \
            dist/*
