name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag to release'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install dependencies
        run: uv sync

      - name: Build package
        run: uv build

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: .github/release-notes-config.yml
        run: |
          gh release create ${{ inputs.tag }} \
            --title "Release ${{ inputs.tag }}" \
            --notes-file <(gh api repos/${{ github.repository }}/releases/generate-notes \
              -F tag_name=${{ inputs.tag }} \
              -F configuration_file_path=$CONFIG_FILE \
              --jq .body) \
            ./dist/*

      # - name: Publish to PyPI
