name: Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh

    - name: Create venv and install dependencies
      run: |
        uv venv .venv
        source .venv/bin/activate
        uv pip install -e ".[dev]"

    - name: Run tests with coverage
      run: |
        source .venv/bin/activate
        pytest --cov=src/git_cleanup --cov-report=xml --cov-report=term-missing

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        fail_ci_if_error: ${{ github.event_name == 'pull_request' && github.base_ref == 'main' }}
        token: ''

    - name: Run pre-commit checks
      run: |
        source .venv/bin/activate
        pre-commit run --all-files
